var annotated =
[
    [ "MKitModel", "interface_m_kit_model.html", "interface_m_kit_model" ],
    [ "MKitModel(Internal)", "category_m_kit_model_07_internal_08.html", "category_m_kit_model_07_internal_08" ],
    [ "MKitModel(Parse)", "category_m_kit_model_07_parse_08.html", "category_m_kit_model_07_parse_08" ],
    [ "MKitModelContext", "interface_m_kit_model_context.html", "interface_m_kit_model_context" ],
    [ "MKitModelContext(Internal)", "category_m_kit_model_context_07_internal_08.html", "category_m_kit_model_context_07_internal_08" ],
    [ "MKitModelPredicateQuery", "interface_m_kit_model_predicate_query.html", null ],
    [ "MKitModelPredicateQuery(Internal)", "category_m_kit_model_predicate_query_07_internal_08.html", "category_m_kit_model_predicate_query_07_internal_08" ],
    [ "MKitModelQuery", "interface_m_kit_model_query.html", "interface_m_kit_model_query" ],
    [ "MKitModelRegistry", "interface_m_kit_model_registry.html", "interface_m_kit_model_registry" ],
    [ "MKitMutableFileArray", "interface_m_kit_mutable_file_array.html", "interface_m_kit_mutable_file_array" ],
    [ "MKitMutableModelArray", "interface_m_kit_mutable_model_array.html", "interface_m_kit_mutable_model_array" ],
    [ "MKitMutableModelArray(Parse)", "category_m_kit_mutable_model_array_07_parse_08.html", "category_m_kit_mutable_model_array_07_parse_08" ],
    [ "MKitMutableOrderedDictionary", "interface_m_kit_mutable_ordered_dictionary.html", null ],
    [ "<MKitNoContext>", "protocol_m_kit_no_context-p.html", null ],
    [ "MKitParseFile", "interface_m_kit_parse_file.html", "interface_m_kit_parse_file" ],
    [ "MKitParseModel", "interface_m_kit_parse_model.html", null ],
    [ "MKitParseModelBinder", "interface_m_kit_parse_model_binder.html", "interface_m_kit_parse_model_binder" ],
    [ "MKitParseModelQuery", "interface_m_kit_parse_model_query.html", null ],
    [ "MKitParseModelQuery(Internal)", "category_m_kit_parse_model_query_07_internal_08.html", "category_m_kit_parse_model_query_07_internal_08" ],
    [ "MKitParseServiceManager", "interface_m_kit_parse_service_manager.html", null ],
    [ "MKitParseServiceManager(Internal)", "category_m_kit_parse_service_manager_07_internal_08.html", "category_m_kit_parse_service_manager_07_internal_08" ],
    [ "MKitParseUser", "interface_m_kit_parse_user.html", "interface_m_kit_parse_user" ],
    [ "MKitReflectedClass", "interface_m_kit_reflected_class.html", "interface_m_kit_reflected_class" ],
    [ "MKitReflectedClass(Internal)", "category_m_kit_reflected_class_07_internal_08.html", "category_m_kit_reflected_class_07_internal_08" ],
    [ "MKitReflectedProperty", "interface_m_kit_reflected_property.html", "interface_m_kit_reflected_property" ],
    [ "MKitReflectionManager", "interface_m_kit_reflection_manager.html", "interface_m_kit_reflection_manager" ],
    [ "MKitServiceFile", "interface_m_kit_service_file.html", "interface_m_kit_service_file" ],
    [ "MKitServiceFile(Internal)", "category_m_kit_service_file_07_internal_08.html", "category_m_kit_service_file_07_internal_08" ],
    [ "MKitServiceKeyChain", "interface_m_kit_service_key_chain.html", "interface_m_kit_service_key_chain" ],
    [ "MKitServiceManager", "interface_m_kit_service_manager.html", "interface_m_kit_service_manager" ],
    [ "MKitServiceModel", "interface_m_kit_service_model.html", "interface_m_kit_service_model" ],
    [ "MKitServiceModelQuery", "interface_m_kit_service_model_query.html", "interface_m_kit_service_model_query" ],
    [ "<MKitServiceUser>", "protocol_m_kit_service_user-p.html", "protocol_m_kit_service_user-p" ],
    [ "NSDate(ModelKit)", "category_n_s_date_07_model_kit_08.html", "category_n_s_date_07_model_kit_08" ],
    [ "NSString(ModelKit)", "category_n_s_string_07_model_kit_08.html", "category_n_s_string_07_model_kit_08" ]
];